- hosts: managed
  become: yes
  user: root

  tasks:
    - name: upgrade all Rocky Linux packages
      yum: 
        name=* 
        state=latest

    - name: update AIDE
      shell: |
        /usr/sbin/aide --update 
        cp /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz

